services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /docker/appdata/jellyfin:/config
      - /mnt/ext-hdd/media:/data/movies
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    networks:
      - mediacenter
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/ext-hdd:/data
    networks:
      - mediacenter
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Spain
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /mnt/ext-hdd/torrent:/data/torrent:rw
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

networks:
  mediacenter:
    driver: bridge
