services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/jellyfin:/config
      - /mnt/ext-hdd/media/tvseries:/data/tvshows
      - /mnt/ext-hdd/media/movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${JELLYFIN_MEMORY}
          cpus: ${JELLYFIN_CPUS}
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/jellyseerr/config:/config
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${JELLYSEERR_MEMORY}
          cpus: ${JELLYSEERR_CPUS}
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/prowlarr:/config
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${PROWLARR_MEMORY}
          cpus: ${PROWLARR_CPUS}
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/ext-hdd:/data
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${RADARR_REPLICAS}
      resources:
        limits:
          memory: ${RADARR_MEMORY}
          cpus: ${RADARR_CPUS}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/ext-hdd:/data
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${SONARR_REPLICAS}
      resources:
        limits:
          memory: ${SONARR_MEMORY}
          cpus: ${SONARR_CPUS}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /mnt/ext-hdd/torrents:/data/torrents
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${QBITTORRENT_MEMORY}
          cpus: ${QBITTORRENT_CPUS}
    restart: unless-stopped

networks:
  mediacenter:
    driver: bridge
