services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/jellyfin:/config
      - /mnt/ext-hdd/media/tvseries:/data/tvshows
      - /mnt/ext-hdd/media/movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${JELLYFIN_REPLICAS}
      resources:
        limits:
          memory: ${JELLYFIN_MEMORY}
          cpus: ${JELLYFIN_CPUS}
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
      - /docker/appdata/plex:/config
      - /mnt/ext-hdd/media/tvseries:/tv
      - /mnt/ext-hdd/media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${PLEX_REPLICAS}
      resources:
        limits:
          memory: ${PLEX_MEMORY}
          cpus: ${PLEX_CPUS}
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8080:8080 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PWD}
      - SERVER_COUNTRIES=Netherlands
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${GLUETUN_MEMORY}
          cpus: ${GLUETUN_CPUS}
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/prowlarr:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${PROWLARR_MEMORY}
          cpus: ${PROWLARR_CPUS}
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/ext-hdd:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${RADARR_REPLICAS}
      resources:
        limits:
          memory: ${RADARR_MEMORY}
          cpus: ${RADARR_CPUS}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/ext-hdd:/data
    networks:
      - mediacenter
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${SONARR_REPLICAS}
      resources:
        limits:
          memory: ${SONARR_MEMORY}
          cpus: ${SONARR_CPUS}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.7
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /mnt/ext-hdd/torrents:/data/torrents
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${QBITTORRENT_MEMORY}
          cpus: ${QBITTORRENT_CPUS}
    restart: unless-stopped
