services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /docker/appdata/jellyfin:/config
      - /mnt/ext-hdd/media:/data/movies
    devices:
      - /dev/dri:/dev/dri
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8080:8080 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp #qbit
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PWD}
      - SERVER_COUNTRIES=Netherlands
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    network_mode: "service:gluetun"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/ext-hdd:/data
    network_mode: "service:gluetun"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.6.7
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /mnt/ext-hdd/torrent:/data/torrent:rw
    network_mode: "service:gluetun"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
